name: drag_handler
version: 1.0.0
author: Christopher Best <bestchris@gmail.com>
description: Encapsulate mouse dragging operations on DOM elements
homepage: https://github.com/sirctseb/drag-handler
environment:
  sdk: '>=2.0.0 <3.0.0'
documentation: http://sirctseb.github.io/drag-handler
dependencies:
  logging: '>=0.9.0 <1.0.0'
